### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by dpfeuffer** [b1gm0/StreetRacing#1]
Hi,
I tried to play your game, but some files are missing:
- blue-car.png
- green-car.png
- yellow-car.png
- coin.png
- ?

**Comment by mozeeez** [comment]
Thanks a lot @dpfeuffer for the bug report. Some files were lost during the upload to GitHub. I've just re-uploaded all files again and tested it. Now it should work :)

**Comment by dpfeuffer** [comment]
Thanks for your quick reply, now it works like a charm. :+1:
